version: 2

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - run: apk add --no-cache bash coreutils curl
      - checkout
      - setup_remote_docker
      - run: ./bin/build

workflows:
  version: 2
  scheduled-build:
    jobs:
      - build:
          context: docker-hub
          filters:
            branches:
              only: master
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
  build:
    jobs:
      - build:
          context: docker-hub
